-- ═══════════════════════════════════════════════════════════════════════════
-- Migration 0001: Initial Schema
-- الرؤية العربية ERP — Foundation Layer
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 1. ULID Generation Function ────────────────────────────────────────────
-- Generates a ULID (Universally Unique Lexicographically Sortable Identifier)
-- 26 characters, Crockford base32 encoding, timestamp-prefixed
-- Requires pgcrypto extension for gen_random_bytes()

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;  -- for fast text search

CREATE OR REPLACE FUNCTION gen_ulid() RETURNS TEXT AS $$
DECLARE
  -- Crockford's Base32 alphabet (no I, L, O, U to avoid confusion)
  encoding  TEXT := '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
  output    TEXT := '';
  now_ms    BIGINT;
  rand_bytes BYTEA;
  i         INT;
BEGIN
  -- 10 characters from timestamp (milliseconds since epoch)
  now_ms := EXTRACT(EPOCH FROM clock_timestamp()) * 1000;
  FOR i IN REVERSE 9..0 LOOP
    output := output || SUBSTR(encoding, (now_ms >> (i * 5) & 31) + 1, 1);
  END LOOP;

  -- 16 characters from random bytes (80 bits of randomness)
  rand_bytes := gen_random_bytes(10);
  FOR i IN 0..9 LOOP
    output := output || SUBSTR(encoding, (GET_BYTE(rand_bytes, i) >> 3 & 31) + 1, 1);
    IF i < 9 THEN
      output := output || SUBSTR(encoding, ((GET_BYTE(rand_bytes, i) & 7) << 2 | GET_BYTE(rand_bytes, i+1) >> 6) & 31 + 1, 1);
    END IF;
  END LOOP;

  RETURN SUBSTR(output, 1, 26);
END;
$$ LANGUAGE plpgsql VOLATILE;

-- ─── 2. Enums ────────────────────────────────────────────────────────────────

CREATE TYPE "UserStatus" AS ENUM ('active', 'inactive', 'locked', 'suspended');
CREATE TYPE "DocumentStatus" AS ENUM ('draft', 'submitted', 'approved', 'rejected', 'posted', 'paid', 'delivered', 'closed', 'cancelled', 'reversed');
CREATE TYPE "JournalEntryStatus" AS ENUM ('draft', 'posted', 'reversed');
CREATE TYPE "WarehouseType" AS ENUM ('main', 'sales_floor', 'receiving', 'quality_hold', 'damaged', 'in_transit', 'consignment');
CREATE TYPE "StocktakingStatus" AS ENUM ('open', 'counting', 'reviewing', 'approved', 'closed');
CREATE TYPE "PricingMethod" AS ENUM ('fixed', 'markup', 'margin', 'formula');
CREATE TYPE "CompanyPlan" AS ENUM ('trial', 'starter', 'business', 'enterprise');
CREATE TYPE "LedgerSide" AS ENUM ('debit', 'credit');
CREATE TYPE "AccountCategory" AS ENUM ('fixed_assets', 'current_assets', 'liabilities', 'equity', 'revenue', 'expense');
CREATE TYPE "AttributeType" AS ENUM ('text', 'color', 'size', 'number', 'boolean');
CREATE TYPE "ProductType" AS ENUM ('storable', 'service', 'raw_material', 'semi_finished', 'custom', 'bundle');
CREATE TYPE "TransferStatus" AS ENUM ('draft', 'approved', 'in_transit', 'received', 'cancelled');

-- ─── 3. Tables (generated by Prisma — listed here for RLS setup) ─────────────
-- NOTE: Prisma runs the actual CREATE TABLE statements via its own migration.
-- This file handles ONLY the custom PostgreSQL features that Prisma can't generate.
-- Run this AFTER the Prisma-generated migration.

-- ─── 4. Row Level Security (RLS) ─────────────────────────────────────────────
-- All tenant-scoped tables enforce company isolation at the DB level.
-- The NestJS API sets these via: SET LOCAL app.current_company = '...'
-- Even if the application has a bug, data from other companies is NEVER returned.

-- Enable RLS on all tenant-scoped tables
DO $$
DECLARE
  tbl TEXT;
  tenant_tables TEXT[] := ARRAY[
    'users', 'roles', 'user_roles',
    'chart_of_accounts', 'accounting_periods', 'journal_entries', 'journal_entry_lines',
    'posting_profiles', 'cost_centers', 'exchange_rates',
    'product_categories', 'product_templates', 'product_variants', 'variant_barcodes',
    'price_lists', 'price_list_items',
    'warehouses', 'inventory_balances', 'stock_ledger_entries',
    'stock_transfers', 'stock_transfer_lines',
    'stocktaking_sessions', 'stocktaking_lines',
    'reorder_points',
    'audit_logs',
    'document_sequences',
    'system_policies'
  ];
BEGIN
  FOREACH tbl IN ARRAY tenant_tables LOOP
    BEGIN
      EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
      EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', tbl);
    EXCEPTION WHEN undefined_table THEN
      -- Table will be created by Prisma migration; RLS applied after
      NULL;
    END;
  END LOOP;
END $$;

-- RLS Policies: company isolation
-- Pattern: users can only see rows where company_id = current_setting('app.current_company')
-- Super Admin bypass: set app.current_company = '*' to see all companies

CREATE OR REPLACE FUNCTION current_company_id() RETURNS UUID AS $$
  SELECT NULLIF(current_setting('app.current_company', true), '')::UUID;
$$ LANGUAGE SQL STABLE;

-- ─── 5. Append-Only Triggers ─────────────────────────────────────────────────
-- AuditLog and StockLedgerEntry are NEVER updated or deleted.
-- These triggers enforce immutability at the database level.

CREATE OR REPLACE FUNCTION prevent_update_delete()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Table % is append-only. Updates and deletes are not permitted.',
    TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Applied to audit_logs (immutable audit trail)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_logs') THEN
    DROP TRIGGER IF EXISTS no_update_audit_logs ON audit_logs;
    CREATE TRIGGER no_update_audit_logs
      BEFORE UPDATE OR DELETE ON audit_logs
      FOR EACH ROW EXECUTE FUNCTION prevent_update_delete();
  END IF;
END $$;

-- Applied to stock_ledger_entries (immutable stock history)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'stock_ledger_entries') THEN
    DROP TRIGGER IF EXISTS no_update_stock_ledger ON stock_ledger_entries;
    CREATE TRIGGER no_update_stock_ledger
      BEFORE UPDATE OR DELETE ON stock_ledger_entries
      FOR EACH ROW EXECUTE FUNCTION prevent_update_delete();
  END IF;
END $$;

-- Applied to journal_entry_lines (accounting lines are immutable after posting)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'journal_entry_lines') THEN
    DROP TRIGGER IF EXISTS no_update_je_lines ON journal_entry_lines;
    CREATE TRIGGER no_update_je_lines
      BEFORE UPDATE OR DELETE ON journal_entry_lines
      FOR EACH ROW EXECUTE FUNCTION prevent_update_delete();
  END IF;
END $$;

-- ─── 6. Double-Entry Balance Check ───────────────────────────────────────────
-- Enforces that every JournalEntry has totalDebitIqd = totalCreditIqd.
-- DB-level guarantee: no unbalanced entry can ever be saved.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'journal_entries') THEN
    ALTER TABLE journal_entries
      DROP CONSTRAINT IF EXISTS balanced_entry;
    ALTER TABLE journal_entries
      ADD CONSTRAINT balanced_entry
      CHECK (total_debit_iqd = total_credit_iqd);
  END IF;
END $$;

-- ─── 7. Period Lock Trigger ───────────────────────────────────────────────────
-- Prevents any INSERT into journal_entries for a closed accounting period.

CREATE OR REPLACE FUNCTION check_period_open()
RETURNS TRIGGER AS $$
DECLARE
  period_status TEXT;
BEGIN
  SELECT status INTO period_status
  FROM accounting_periods
  WHERE id = NEW.period_id;

  IF period_status != 'open' THEN
    RAISE EXCEPTION 'Cannot post to a % accounting period', period_status
      USING ERRCODE = 'check_violation',
            HINT = 'Open the period first or create a new one';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'journal_entries') THEN
    DROP TRIGGER IF EXISTS enforce_period_lock ON journal_entries;
    CREATE TRIGGER enforce_period_lock
      BEFORE INSERT ON journal_entries
      FOR EACH ROW EXECUTE FUNCTION check_period_open();
  END IF;
END $$;

-- ─── 8. Indexes for Performance ──────────────────────────────────────────────
-- Created separately from Prisma schema to use advanced PostgreSQL index features.

-- Fast email lookup (case-insensitive)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
    CREATE INDEX IF NOT EXISTS idx_users_email_ci
      ON users USING btree (lower(email), company_id)
      WHERE deleted_at IS NULL;
  END IF;
END $$;

-- Barcode lookup (primary + company scoped)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'variant_barcodes') THEN
    CREATE INDEX IF NOT EXISTS idx_barcodes_lookup
      ON variant_barcodes (barcode, company_id);
  END IF;
END $$;

-- Stock ledger chronological queries (most common: last entries for a variant)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'stock_ledger_entries') THEN
    CREATE INDEX IF NOT EXISTS idx_stock_ledger_variant_time
      ON stock_ledger_entries (variant_id, warehouse_id, created_at DESC);
  END IF;
END $$;

-- Journal entries by period (for period close queries)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'journal_entries') THEN
    CREATE INDEX IF NOT EXISTS idx_je_period_company
      ON journal_entries (period_id, company_id, created_at DESC)
      WHERE status = 'posted';
  END IF;
END $$;

-- Audit trail queries (entity history)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_logs') THEN
    CREATE INDEX IF NOT EXISTS idx_audit_entity
      ON audit_logs (company_id, entity_type, entity_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_audit_user
      ON audit_logs (company_id, user_id, created_at DESC);
  END IF;
END $$;

-- Full-text search on product names (Arabic + English)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'product_templates') THEN
    CREATE INDEX IF NOT EXISTS idx_products_name_trgm
      ON product_templates USING gin (name_ar gin_trgm_ops, name_en gin_trgm_ops);
  END IF;
END $$;

-- ─── 9. Updated_at auto-trigger ──────────────────────────────────────────────
-- Automatically sets updated_at on every UPDATE (for tables that have it).

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Applied dynamically to all tables with updated_at column
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT table_name
    FROM information_schema.columns
    WHERE column_name = 'updated_at'
      AND table_schema = 'public'
      AND table_name NOT IN ('audit_logs', 'stock_ledger_entries', 'journal_entry_lines')
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS set_updated_at ON %I;
       CREATE TRIGGER set_updated_at
         BEFORE UPDATE ON %I
         FOR EACH ROW EXECUTE FUNCTION update_updated_at()',
      tbl, tbl
    );
  END LOOP;
END $$;
