/**
 * License seed for the Al-Ruya ERP — creates plans + an active Enterprise
 * Subscription for the singleton company (code RUA).
 *
 * Idempotent: re-running upserts the plans and ensures exactly one
 * non-terminal subscription exists for the company. Safe to run repeatedly.
 *
 * What this enables:
 *   1. Re-enabling the global LicenseGuard (`LICENSE_GUARD_DISABLED=0` on
 *      VPS) without 403'ing every authed request — the seeded Subscription
 *      satisfies FeatureCacheService.get(companyId).
 *   2. The /licensing/me/features endpoint can return the actual feature
 *      catalog instead of an empty stub.
 *
 * Run with:
 *   docker compose exec -T api sh -c "cd /app/apps/api && npx tsx prisma/license-seed.ts"
 *
 * Or via the workflow_dispatch in `.github/workflows/license-seed.yml`.
 */
import { PrismaClient, Prisma, $Enums } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import { seedPlans, PLAN_CODES } from './seed/plans.seed';

// I040 — Prisma 7 driver-adapter pattern. Standalone scripts need to wire
// the pg Pool + PrismaPg adapter just like PrismaService does in the app.
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🔐 License seeder starting...');

  // Step 1: Ensure plans exist (idempotent).
  await seedPlans(prisma);

  // Step 2: Find the singleton company.
  const company = await prisma.company.findFirst({ where: { code: 'RUA' } });
  if (!company) throw new Error('Company RUA not found — run seed.ts first');
  console.log(`✅ company: ${company.id} (${company.code})`);

  // Step 3: Find the Enterprise plan (full feature set).
  const plan = await prisma.plan.findUnique({
    where: { code: PLAN_CODES.ENTERPRISE },
  });
  if (!plan) throw new Error('Enterprise plan not found after seedPlans()');
  console.log(`✅ plan: ${plan.id} (${plan.code})`);

  // Step 4: Idempotency guard — return any non-terminal subscription.
  const existing = await prisma.subscription.findFirst({
    where: {
      companyId: company.id,
      status: {
        in: [
          $Enums.SubscriptionStatus.pending,
          $Enums.SubscriptionStatus.trial,
          $Enums.SubscriptionStatus.grace,
          $Enums.SubscriptionStatus.active,
        ],
      },
    },
    orderBy: { createdAt: 'desc' },
  });

  if (existing) {
    console.log(
      `ℹ️  existing subscription found: ${existing.id} (status=${existing.status}, plan=${existing.planId}). ` +
        `Re-asserting active state without creating a duplicate.`,
    );

    if (existing.status !== $Enums.SubscriptionStatus.active) {
      // If the existing row is in trial/grace/pending, promote it to active.
      const now = new Date();
      const oneYearFromNow = new Date(now);
      oneYearFromNow.setFullYear(oneYearFromNow.getFullYear() + 1);

      await prisma.subscription.update({
        where: { id: existing.id },
        data: {
          status: $Enums.SubscriptionStatus.active,
          planId: plan.id,
          startedAt: existing.startedAt ?? now,
          currentPeriodStartAt: now,
          currentPeriodEndAt: oneYearFromNow,
          billingCycle: $Enums.BillingCycle.annual,
          priceIqd: new Prisma.Decimal(plan.annualPriceIqd),
        },
      });
      console.log(
        `✅ existing subscription promoted to active (period: ${now.toISOString()} → ${oneYearFromNow.toISOString()})`,
      );
    }

    console.log('🎉 license-seed complete (existing subscription).');
    return;
  }

  // Step 5: Create a fresh active Enterprise subscription.
  const now = new Date();
  const oneYearFromNow = new Date(now);
  oneYearFromNow.setFullYear(oneYearFromNow.getFullYear() + 1);

  const sub = await prisma.subscription.create({
    data: {
      companyId: company.id,
      planId: plan.id,
      status: $Enums.SubscriptionStatus.active,
      billingCycle: $Enums.BillingCycle.annual,
      startedAt: now,
      currentPeriodStartAt: now,
      currentPeriodEndAt: oneYearFromNow,
      priceIqd: new Prisma.Decimal(plan.annualPriceIqd),
      notes: 'Initial license seed (Enterprise, annual). Generated by license-seed.ts.',
    },
  });

  console.log(`✅ subscription created: ${sub.id}`);
  console.log(
    `   plan=Enterprise · cycle=annual · price=${sub.priceIqd.toString()} IQD · ` +
      `period=${now.toISOString().slice(0, 10)} → ${oneYearFromNow.toISOString().slice(0, 10)}`,
  );
  console.log('🎉 license-seed complete (new subscription).');
  console.log('');
  console.log('Next step: set LICENSE_GUARD_DISABLED=0 in VPS .env and');
  console.log('  docker compose -f docker-compose.bootstrap.yml up -d --force-recreate api');
  console.log('to re-enable the global LicenseGuard now that a subscription exists.');
}

main()
  .catch((e) => {
    console.error('❌ License seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
