/** @type {import('next').NextConfig} */
const isWindows = process.platform === 'win32';
const nextConfig = {
  reactStrictMode: true,
  // Standalone output for Docker minimal-image deploy. Disabled on
  // Windows because the symlinks generated by Next.js break local dev.
  ...(isWindows ? {} : { output: 'standalone' }),
  i18n: {
    locales: ['ar', 'en', 'ku'],
    defaultLocale: 'ar',
  },
  images: {
    formats: ['image/webp'],
    remotePatterns: [
      // Production: API + MinIO are exposed under ibherp.cloud (and a
      // dedicated subdomain once T55-shop DNS lands). Legacy al-ruya.iq
      // patterns were dropped — the prior deploy on this VPS used those
      // hostnames but the current domain is ibherp.cloud.
      { protocol: 'https', hostname: 'ibherp.cloud' },
      { protocol: 'https', hostname: 'shop.ibherp.cloud' },
      { protocol: 'https', hostname: 'minio.ibherp.cloud' },
    ],
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options',        value: 'SAMEORIGIN' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy',        value: 'strict-origin-when-cross-origin' },
        ],
      },
    ];
  },
};
module.exports = nextConfig;
